/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Productos extends javax.swing.JFrame {

    /**
     * Creates new form Productos
     */
    VerificarCedula c = new VerificarCedula();
    public DefaultTableModel model;

    public Productos() {
        initComponents();
        cargarTabla("");
//        h1 = new Thread((Runnable) this);
        // h1.start();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField_BuscadorProd = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_CódigoProd = new javax.swing.JTextField();
        jTextField_NombreProd = new javax.swing.JTextField();
        jTextField_ColorProd = new javax.swing.JTextField();
        jTextField_CantidadProd = new javax.swing.JTextField();
        jTextField_PrecVentProd = new javax.swing.JTextField();
        jTextField_PrecCosProd = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldCategoria_Prod = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Productos = new javax.swing.JTable();
        jButton_IngresarProducto = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Productos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(0, 51, 51))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 0, 51));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jTextField_BuscadorProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_BuscadorProdKeyReleased(evt);
            }
        });

        jButton1.setText("Buscar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jTextField_BuscadorProd, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextField_BuscadorProd)
                .addComponent(jButton1))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(0, 51, 51))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Código:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Cantidad:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Precio de Venta:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Precio de Compra:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Color:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Tallas:");

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setText("Ingresar");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Categoria:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_NombreProd)
                            .addComponent(jTextField_ColorProd, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(jTextField_CódigoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_CantidadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(32, 32, 32)
                        .addComponent(jButton2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_PrecVentProd, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(jTextField_PrecCosProd)
                            .addComponent(jTextFieldCategoria_Prod))))
                .addGap(45, 45, 45))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_CódigoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_PrecVentProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_NombreProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_PrecCosProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_ColorProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldCategoria_Prod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_CantidadProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jButton2))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTable_Productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable_Productos);

        jButton_IngresarProducto.setText("Ingresar Producto");
        jButton_IngresarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_IngresarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(257, 257, 257))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jButton_IngresarProducto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_IngresarProducto)
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void Insertarfilas() {

    }

    public void TituloTablaProveedores() {

    }
    private void jButton_IngresarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_IngresarProductoActionPerformed
        // TODO add your handling code here:
        guardarProductos();
        cargarTabla("");
    }//GEN-LAST:event_jButton_IngresarProductoActionPerformed

    private void jTextField_BuscadorProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_BuscadorProdKeyReleased
        // TODO add your handling code here:
         cargarTabla(jTextField_BuscadorProd.getText());
    }//GEN-LAST:event_jTextField_BuscadorProdKeyReleased
    public void guardarProductos() {
        Connection cn = (new ConexionBD()).conectar();

        if (jTextField_CódigoProd.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingresar Codigo");
            jTextField_CódigoProd.requestFocus();
        } else if (jTextField_NombreProd.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingresar nombre");
            jTextField_NombreProd.requestFocus();
        } else if (jTextField_ColorProd.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingresar color");
            jTextField_ColorProd.requestFocus();
        } else if (jTextField_CantidadProd.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingresar cantidad");
            jTextField_CantidadProd.requestFocus();
        } else if (jTextField_PrecVentProd.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingresar Precio Venta");
            jTextField_PrecVentProd.requestFocus();
        } else if (jTextField_PrecCosProd.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingresar precio Compra");
            jTextField_PrecCosProd.requestFocus();
        } else if (jTextFieldCategoria_Prod.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingresar Categoria");
            jTextFieldCategoria_Prod.requestFocus();
        } else {
            try {

                String Codigo = jTextField_CódigoProd.getText().toUpperCase();
                String Nombre = jTextField_NombreProd.getText().toUpperCase();
                String Color = jTextField_ColorProd.getText().toUpperCase();
                String Cantidad = jTextField_CantidadProd.getText().toUpperCase();
                String PrecioVenta = jTextField_PrecVentProd.getText().toUpperCase();
                String PrecioCompra = jTextField_PrecCosProd.getText().toUpperCase();
                String Categoria = jTextFieldCategoria_Prod.getText().toUpperCase();

                String sql = "insert into productos (COD_PRO, NOM_PRO, COL_PRO, CANT_PRO, PRE_VEN_PRO,PRE_COMP_PRO,CAT_PRO)values(?,?,?,?,?,?,?)";

                PreparedStatement psd = cn.prepareStatement(sql);
                psd.setString(1, Codigo);
                psd.setString(2, Nombre);
                psd.setString(3, Color);
                psd.setString(4, Cantidad);
                psd.setString(5, PrecioVenta);
                psd.setString(6, PrecioCompra);
                psd.setString(7, Categoria);

                if (psd.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(null, "Se ha insertado el dato");
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "No se ha insertado el dato");
            }
        }

    }

    public void cargarDatos() {
        jTable_Productos.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (jTable_Productos.getSelectedRow() != -1) {
                    int fila = jTable_Productos.getSelectedRow();
                    jTextField_CódigoProd.setText(jTable_Productos.getValueAt(fila, 0).toString());
                    jTextField_NombreProd.setText(jTable_Productos.getValueAt(fila, 1).toString());
                    jTextField_ColorProd.setText(jTable_Productos.getValueAt(fila, 2).toString());
                    jTextField_CantidadProd.setText(jTable_Productos.getValueAt(fila, 3).toString());
                    jTextField_PrecVentProd.setText(jTable_Productos.getValueAt(fila, 4).toString());
                    jTextField_PrecCosProd.setText(jTable_Productos.getValueAt(fila, 5).toString());
                    jTextFieldCategoria_Prod.setText(jTable_Productos.getValueAt(fila, 6).toString());
                    //desbloquear();                    
                }
            }
        });
    }

    public void limpiar() {
//        txtCedula.setText("");
//        txtNombre.setText("");
//        txtApellido.setText("");
//        txtDireccion.setText("");
//        txtBuscarCedula.setText("");
//        txtTelefono.setText("");
    }

    public void bloquear() {
//        txtCedula.setEnabled(true);
//        txtNombre.setEnabled(true);
//        txtApellido.setEnabled(true);
//        txtDireccion.setEnabled(true);
//        txtTelefono.setEnabled(true);
//        btActualizar.setEnabled(false);
//        btEliminar.setEnabled(false);
//        btCancelar.setEnabled(false);
    }

    public void desbloquear() {
//        txtNombre.setEnabled(true);
//        txtApellido.setEnabled(true);
//        txtDireccion.setEnabled(true);
//        txtTelefono.setEnabled(true);
//        btActualizar.setEnabled(true);
//        btEliminar.setEnabled(true);
//        btCancelar.setEnabled(true);
//        txtBuscarCedula.setEnabled(true);

    }

    public void cargarTabla(String dato) {
        Connection cn = (new ConexionBD()).conectar();

        String[] titulo = {"Cedula", "Nombre", "Apellido", "Direccion", "Teléfono"};
        String[] registros = new String[7];
        String sql;
        sql = "SELECT * FROM PRODUCTOS WHERE COD_PRO LIKE '" + dato + "%'";
        model = new DefaultTableModel(null, titulo);
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                registros[0] = rs.getString("COD_PRO");
                registros[1] = rs.getString("NOM_PRO");
                registros[2] = rs.getString("COL_PRO");
                registros[3] = rs.getString("CANT_PRO");
                registros[4] = rs.getString("PRE_VEN_PRO");
                registros[5] = rs.getString("PRE_COMP_PRO");
                registros[6] = rs.getString("CAT_PRO");
                model.addRow(registros);
                jTable_Productos.setModel(model);

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "La tabla PRODUCTOS tiene problemas al cargarse\n" + ex);
        }
    }

    public void actualizarEmpleados() {
        Connection cn = (new ConexionBD()).conectar();

        String sql;
        sql = "update cajeros set  NOM_EMP ='" + jTextField_NombreProd.getText() + "',"
                + "APE_EMP='" + jTextField_ColorProd.getText() + "',"
                + "DIR_EMP='" + jTextField_CantidadProd.getText() + "',"
                + "TEL_EMP='" + jTextField_PrecVentProd.getText() + "'"
                 + "DIR_EMP='" + jTextField_PrecCosProd.getText() + "',"
                + "TEL_EMP='" + jTextFieldCategoria_Prod.getText() + "'"
                + "where CED_EMP='" + jTextField_CódigoProd.getText() + "'";
        try {
            PreparedStatement psd = cn.prepareStatement(sql);
            int n = psd.executeUpdate();//Ejecutar el 
            if (n > 0) {
                JOptionPane.showMessageDialog(this, "Se actualizo correctamente");
                cargarTabla("");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "No se pudo actualizar" + ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_IngresarProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable_Productos;
    private javax.swing.JTextField jTextFieldCategoria_Prod;
    private javax.swing.JTextField jTextField_BuscadorProd;
    private javax.swing.JTextField jTextField_CantidadProd;
    private javax.swing.JTextField jTextField_ColorProd;
    private javax.swing.JTextField jTextField_CódigoProd;
    private javax.swing.JTextField jTextField_NombreProd;
    private javax.swing.JTextField jTextField_PrecCosProd;
    private javax.swing.JTextField jTextField_PrecVentProd;
    // End of variables declaration//GEN-END:variables
}
